# Generated by Django 4.0.3 on 2022-03-21 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsfordinner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsfordinner.dinner')),
            ],
        ),
    ]
