# Generated by Django 4.0.3 on 2022-03-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsfordinner', '0002_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner',
            old_name='Details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dinner',
            old_name='Name',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='dinner',
            old_name='Notes',
            new_name='ingredient',
        ),
        migrations.AddField(
            model_name='dinner',
            name='mesurement',
            field=models.TextField(blank=True),
        ),
    ]
